INSERT INTO food(name, image_url, price_in_cents,description) VALUES('eel bowl','eel',3000,'It is called Unadon( an abbreviation for unagi donburi, "eel bowl"). It consists of a donburi type large bowl filled with steamed white rice, and topped with fillets of eel (unagi) grilled in a style known as kabayaki, similar to teriyaki. ');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('miso soup','misosoup',200,'a traditional Japanese soup consisting of a dashi stock into which softened miso paste is mixed. In addition, there are many optional ingredients (various vegetables, tofu, abura-age, etc.) that may be added depending on regional and seasonal recipes, and personal preference.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('stewed meat and potatoes','nikujaga',600,' It is an iconic Japanese home-cooked dish, known as “Ofukuro no Aji” – taste of mother’s cooking. For many, nikujaga is an honest-to-goodness comfort food.

Potatoes make up the majority of the dish, with some thinly sliced beef or pork, onion, shirataki noodles (ito konnyaku), and colorful mix of vegetables. In western Japan, nikujaga typically features beef while pork is more commonly used in eastern Japan.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('rice ball','riceball',300, 'It is made from white rice formed into triangular or cylindrical shapes and often wrapped in nori.[a] Traditionally, an onigiri is filled with pickled ume (umeboshi), salted salmon, katsuobushi, kombu, tarako, mentaiko, takanazuke (pickled takana) or any other salty or sour ingredient as a natural preservative.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('oden','oden',1000, 'A classic winter comfort dish in Japan, Oden is a one-pot dish with an assortment of fish balls, fish cakes, deep-fried tofu, hard-boiled eggs, konnyaku, and some vegetables simmered in soy sauce-based dashi broth.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('salmon bowl','salmonbowl',1200, 'Satisfy your sushi craving with this Salmon Sashimi Bowl! Topped with fresh sashimi-grade salmon, salmon roe (ikura), and shredded nori, this Japanese donburi is light and super tasty. ');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('sashimi','sashimi',2000, 'It is a Japanese delicacy consisting of fresh raw fish or meat sliced into thin pieces and often eaten with soy sauce.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('soba','soba',1400, 'Soba noodles are noodles made of buckwheat flour, roughly as thick as spaghetti, and prepared in various hot and cold dishes. Soba dishes are very popular and easily available nationwide. As 100% buckwheat soba noodles tend to be brittle, many restaurants add some wheat flour when preparing their noodles. Depending on the shop, the percentage of buckwheat flour in soba noodles typically ranges between 40% and 100%.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('sukiyaki','sukiyaki',1800, 'It is a Japanese dish that is prepared and served in the nabemono (Japanese hot pot) style. It consists of meat (usually thinly sliced beef) which is slowly cooked or simmered at the table, alongside vegetables and other ingredients, in a shallow iron pot in a mixture of soy sauce, sugar, and mirin. The ingredients are usually dipped in a small bowl of raw, beaten eggs after being cooked in the pot, and then eaten.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('sushi','sushi',2400, 'Sushi is a Japanese dish featuring specially prepared rice and usually some type of fish or seafood, often raw, but sometimes cooked. And though you might automatically associate the word sushi with raw fish, it is actually the rice that is the most important ingredient. Indeed, the word "sushi" refers to the sour flavor of the vinegared rice. Regardless of the toppings or fillings, sushi always includes rice.');
INSERT INTO food(name, image_url, price_in_cents,description) VALUES('udon','udon',1300, 'Thick noodle made from wheat flour, used in Japanese cuisine. It is a comfort food for many Japanese people. There are a variety of ways it is prepared and served. Its simplest form is in a hot soup as kake udon with a mild broth called kakejiru made from dashi, soy sauce, and mirin. It is usually topped with thinly chopped scallions. Other common toppings include prawn tempura, kakiage (mixed tempura fritter), abura-age (sweet, deep-fried tofu pouches), kamaboko (sliced fish cake), and shichimi spice added to taste.');
